using System.Collections.ObjectModel;
using System.Numerics;

namespace Arcraven.Avalonia.ResourcesLib.Models;

/// <summary>
/// Represents an event generated by or targeting an interactable entity 
/// (e.g., Robot, Drone, Operator).
/// </summary>
/// <summary>
/// Represents an event generated by or targeting an interactable entity 
/// (e.g., Robot, Drone, Operator). Now includes telemetry for autonomous systems.
/// </summary>
public class RCEvent : Event
{
    public RCEvent(
        string name,
        string label,
        Severity severity,
        bool isControllable = true,
        Vector3? position = null,
        IEnumerable<Sensor>? sensors = null,
        IEnumerable<Joint>? joints = null,
        IEnumerable<Camera>? cameras = null,
        Guid? id = null,
        Guid? sourceGuid = null,
        TimeSpan? duration = null,
        bool isOngoing = false,
        string description = "",
        DateTimeOffset? startingTime = null,
        bool isAcknowledged = false)
        : base(name, label, severity, id, duration, isOngoing, sourceGuid, description, startingTime, isAcknowledged)
    {
        IsControllable = isControllable;
        Position = position ?? Vector3.Zero;
        
        // Initialize collections with provided data or empty lists
        Sensors = sensors != null ? new ObservableCollection<Sensor>(sensors) : new ObservableCollection<Sensor>();
        Joints = joints != null ? new ObservableCollection<Joint>(joints) : new ObservableCollection<Joint>();
        Cameras = cameras != null ? new ObservableCollection<Camera>(cameras) : new ObservableCollection<Camera>();
    }

    public RCEvent() 
    {
        Sensors = new ObservableCollection<Sensor>();
        Joints = new ObservableCollection<Joint>();
        Cameras = new ObservableCollection<Camera>();
    }

    private bool _isControllable;
    /// <summary>
    /// Indicates if the source of this event accepts return commands.
    /// </summary>
    public bool IsControllable
    {
        get => _isControllable;
        set => Set(ref _isControllable, value);
    }

    // ==========================================
    // Spatial Data
    // ==========================================
    private Vector3 _position;
    /// <summary>
    /// Represents the physical 3D coordinates of the robot (X, Y, Z).
    /// </summary>
    public Vector3 Position
    {
        get => _position;
        set => Set(ref _position, value);
    }
    
    public float Latitude => _position.X;
    public float Longitude => _position.Y;
    public float Altitude => _position.Z;

    // ==========================================
    // Telemetry Collections
    // ==========================================
    
    private ObservableCollection<Sensor> _sensors;
    public ObservableCollection<Sensor> Sensors
    {
        get => _sensors;
        set => Set(ref _sensors, value);
    }

    private ObservableCollection<Joint> _joints;
    public ObservableCollection<Joint> Joints
    {
        get => _joints;
        set => Set(ref _joints, value);
    }

    private ObservableCollection<Camera> _cameras;
    public ObservableCollection<Camera> Cameras
    {
        get => _cameras;
        set => Set(ref _cameras, value);
    }

    // Placeholder for future Command/RPC logic
    public void SendCommand(string command)
    {
        // Implementation for remote control logic would go here
    }
}